// Separate file for each data structure to keep the code organized and maintainable.
const employees = [
  {
    id: 1042,
    name: "Aarav Sharma",
    age: 29,
    department: "Engineering",
    role: "Senior Frontend Developer",
    experience: 6,
    salary: 1850000,
    location: "Pune",
    skills: ["React", "JavaScript", "TypeScript", "Node.js"],
    status: "active",
  },
  {
    id: 1018,
    name: "Priya Mehta",
    age: 27,
    department: "Engineering",
    role: "Backend Developer",
    experience: 5,
    salary: 1620000,
    location: "Mumbai",
    skills: ["Node.js", "Express", "MongoDB", "AWS"],
    status: "active",
  },
  {
    id: 1087,
    name: "Rohan Desai",
    age: 36,
    department: "Engineering",
    role: "Engineering Manager",
    experience: 12,
    salary: 3200000,
    location: "Bangalore",
    skills: ["Java", "AWS", "Kubernetes", "System Design"],
    status: "active",
  },
  {
    id: 1005,
    name: "Sneha Patil",
    age: 26,
    department: "Quality",
    role: "QA Engineer",
    experience: 4,
    salary: 1250000,
    location: "Hyderabad",
    skills: ["Playwright", "Cypress", "Jest", "Selenium"],
    status: "active",
  },
  {
    id: 1063,
    name: "Vikram Joshi",
    age: 31,
    department: "Infrastructure",
    role: "DevOps Engineer",
    experience: 7,
    salary: 2100000,
    location: "Chennai",
    skills: ["Docker", "Kubernetes", "Jenkins", "Terraform", "AWS"],
    status: "active",
  },
  {
    id: 1095,
    name: "Neha Kapoor",
    age: 30,
    department: "Design",
    role: "Product Designer",
    experience: 6,
    salary: 1750000,
    location: "Delhi",
    skills: ["Figma", "UX Research", "Prototyping"],
    status: "active",
  },
  {
    id: 1029,
    name: "Karan Shah",
    age: 25,
    department: "Engineering",
    role: "Frontend Developer",
    experience: 3,
    salary: 1050000,
    location: "Ahmedabad",
    skills: ["React", "JavaScript", "Redux", "CSS"],
    status: "active",
  },
  {
    id: 1074,
    name: "Ananya Rao",
    age: 28,
    department: "Data",
    role: "Data Engineer",
    experience: 5,
    salary: 1900000,
    location: "Bangalore",
    skills: ["Python", "SQL", "Spark", "AWS"],
    status: "active",
  },
  {
    id: 1036,
    name: "Rahul Verma",
    age: 34,
    department: "Engineering",
    role: "Full Stack Developer",
    experience: 9,
    salary: 2350000,
    location: "Pune",
    skills: ["React", "Node.js", "MongoDB", "Docker"],
    status: "active",
  },
  {
    id: 1051,
    name: "Isha Nair",
    age: 24,
    department: "Marketing",
    role: "Marketing Analyst",
    experience: 2,
    salary: 850000,
    location: "Mumbai",
    skills: ["Excel", "SQL", "Power BI"],
    status: "active",
  },
  {
    id: 1102,
    name: "Aditya Kulkarni",
    age: 32,
    department: "Engineering",
    role: "Software Architect",
    experience: 10,
    salary: 2850000,
    location: "Pune",
    skills: ["JavaScript", "Node.js", "AWS", "System Design"],
    status: "active",
  },
  {
    id: 1011,
    name: "Meera Iyer",
    age: 29,
    department: "Finance",
    role: "Financial Analyst",
    experience: 6,
    salary: 1450000,
    location: "Chennai",
    skills: ["Excel", "SQL", "Power BI", "Python"],
    status: "inactive",
  },
];
